name: sistema_logistico_delivery
description: Sistema profesional de gestión logística y delivery 2026.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # Estado y Navegación
  flutter_riverpod: ^2.4.9
  go_router: ^17.1.0
  
  # Base de Datos y Backend
  firebase_core: ^4.5.0
  cloud_firestore: ^6.1.3
  firebase_auth: ^6.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Utilidades
  uuid: ^4.2.2
  intl: ^0.20.2
  font_awesome_flutter: ^11.0.0
  fl_chart: ^1.1.1
  path_provider: ^2.1.2
  share_plus: ^12.0.1
  pdf: ^3.10.7
  printing: ^5.11.1
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true